# prezto config
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/zsh/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/prezto/init.zsh"
fi

# antigen
source ~/.dotfiles/zsh/antigen/antigen.zsh

# _source my own aliases
source ~/.dotfiles/zsh/zsh/zbindings
source ~/.dotfiles/zsh/dev/zenv
source ~/.dotfiles/zsh/aliases/zgit
source ~/.dotfiles/zsh/aliases/zvim
source ~/.dotfiles/zsh/aliases/zcd
source ~/.dotfiles/zsh/functions/zfunctions
source ~/.dotfiles/zsh/aliases/zdev
source ~/.dotfiles/zsh/aliases/zalias
source ~/.dotfiles/zsh/aliases/zapp

# autojump > cd
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# 'thefuck' command correction 
eval "$(thefuck --alias)"

# neat colour schemes to use
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# tabtab source for yarn package
# uninstall by removing these lines or running `tabtab uninstall yarn`
[[ -f /Users/nikivi/.yarn-cache/.global/node_modules/tabtab/.completions/yarn.zsh ]] && . /Users/nikivi/.yarn-cache/.global/node_modules/tabtab/.completions/yarn.zsh


# zsh modules
antigen bundle wbinglee/zsh-wakatime

antigen apply

# need it
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

