# prezto config
source ~/.dotfiles/zsh/prezto/init.zsh

# _plugin manager
source <(antibody init) 

# source all plugins
antibody bundle < ~/.dotfiles/zsh/plugins/plugins.txt

# _source my own aliases
source ~/.dotfiles/zsh/zsh/zbindings
source ~/.dotfiles/zsh/dev/zenv
source ~/.dotfiles/zsh/aliases/zgit
source ~/.dotfiles/zsh/aliases/zvim
source ~/.dotfiles/zsh/aliases/zcd
source ~/.dotfiles/zsh/functions/zfunctions
source ~/.dotfiles/zsh/aliases/zdev
source ~/.dotfiles/zsh/aliases/zalias
source ~/.dotfiles/zsh/aliases/zapp

# _secret config
source ~/.secrets

# default editor
export EDITOR='code'

# autojump > cd
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# 'thefuck' command correction 
eval "$(thefuck --alias)"

# neat colour schemes to use
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tabtab source for yarn package
# uninstall by removing these lines or running `tabtab uninstall yarn`
[[ -f /Users/nikivi/.yarn-cache/.global/node_modules/tabtab/.completions/yarn.zsh ]] && . /Users/nikivi/.yarn-cache/.global/node_modules/tabtab/.completions/yarn.zsh


