# _exports
export EDITOR='nvim'
export DOTFILES="$HOME/.dotfiles"

# _source aliases
source ~/.dotfiles/zsh/zsh/zbindings
source ~/.dotfiles/zsh/dev/zenv
source ~/.dotfiles/zsh/aliases/zgit
source ~/.dotfiles/zsh/aliases/zvim
source ~/.dotfiles/zsh/aliases/zcd
source ~/.dotfiles/zsh/functions/zfunctions
source ~/.dotfiles/zsh/aliases/zdev
source ~/.dotfiles/zsh/aliases/zalias
source ~/.dotfiles/zsh/aliases/zapp

setopt autocd

# _secret configs
source ~/.secrets

# _load zsh plugins
source ~/.zsh_plugins.sh

# 'thefuck' command correction
eval "$(thefuck --alias)"

# neat colour schemes to use
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# _yarn autocomplete
[[ -f /Users/nikivi/.yarn-cache/.global/node_modules/tabtab/.completions/yarn.zsh ]] && . /Users/nikivi/.yarn-cache/.global/node_modules/tabtab/.completions/yarn.zsh


# TODO: does not work
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

